[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

# --------------------------------------
# 🔲 Black — Code Formatter
# --------------------------------------
[tool.black]
line-length = 88
target-version = ["py313"]
include = '\.pyi?$'
skip-string-normalization = false

# --------------------------------------
# 🔀 isort — Import Sorter
# --------------------------------------
[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ["imagefox"]
known_third_party = []

# --------------------------------------
# 🧼 Ruff — Linter + Import Sort + More
# --------------------------------------
[tool.ruff]
line-length = 88
target-version = "py313"
select = ["E", "F", "W", "I"]
ignore = ["E203", "E501"]  # Compatible with Black
exclude = ["__pycache__", "tests/__init__.py"]

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

# --------------------------------------
# 🧪 Pytest — Test Configuration
# --------------------------------------
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --tb=short"
testpaths = ["tests"]
xfail_strict = true
filterwarnings = [
  "ignore::DeprecationWarning"
]

# --------------------------------------
# 🧪 Coverage.py — Code Coverage Reporting
# --------------------------------------
[tool.coverage.run]
branch = true
source = ["imagefox"]

[tool.coverage.report]
omit = ["tests/*", "*/__init__.py"]
show_missing = true
skip_covered = true
precision = 2
fail_under = 90

# --------------------------------------
# 🔍 Mypy — Static Type Checker
# --------------------------------------
[tool.mypy]
python_version = "3.13"
strict = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = false
ignore_missing_imports = true
show_error_codes = true
pretty = true
no_implicit_optional = true
files = ["imagefox", "tests"]
